version: '3'
services:
  # Ton serveur Python (main.py)
  app-server:
    build: .
    restart: always
    env_file: .env
    volumes:
      # Permet d'éditer les IDs Discord à chaud, sans rebuild de l'image
      - ./discord_links.json:/app/discord_links.json

  # Le tunnel Ngrok qui rend ton serveur accessible
  ngrok-tunnel:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - http
      - --domain=decomposable-untawdry-shaquana.ngrok-free.dev
      - app-server:8000
    depends_on:
      - app-server